### ISSUE TITLE
'function' is not a member of 'std'

### ISSUE THREAD

**Issue by yuyadanyadan** [nagadomi/waifu2x-caffe#1]
lltcggie-caffe/src/caffe/util/cudnn_func.cpp:13:7:error: template declaration of 'cudnnStatus_t caffe::cudnn::FindAlgorithmEx'

cuda8.0 + cudnnV5 + ubuntu14.04

what's wrong???

**Comment by nagadomi** [comment]
your gcc seems does not support c++11. use gcc 4.8 or later.

**Comment by yuyadanyadan** [comment]
my g++ is 4.8 version! It is the complier is not my g++. It use an older version! Now I change it! Thank you !

在 2016-08-17 22:49:58，"nagadomi" notifications@github.com 写道：

your gcc seems does not support c++11. use gcc 4.8 or later.
