### ISSUE TITLE
New models work in ubuntu version of waifu2x-caffe?

### ISSUE THREAD

**Issue by sjscotti** [nagadomi/waifu2x-caffe#4]
Hi!
I noticed in the lltcggie/waifu2x-caffe repository that there are 2 new models under waifu2x-caffe/bin/models.  They are called cunet and upresnet10.  I would like to try these models out with this ubuntu version.  Can I just copy over the two folders with the model files from lltcggie's repository into the model folder for the ubuntu version and select one of these models with the `--model_dir` option, or does the code itself need to be modified to use these new models?
Thanks in advance!

**Comment by nagadomi** [comment]
it needs to merge the latest version of waifu2x-caffe.

**Comment by sjscotti** [comment]
Thanks for the speedy reply!  So do I just bring some of the routines from lltcggie's repository over or is it more complicated than that?

**Comment by nagadomi** [comment]
I've merged recent changes.
upresnet10 and cunet work.
However,  Shift JIS issue has not been fixed.

You can use it by rebuilding lltcggie-caffe and waifu2x-caffe after git pull.

**Comment by sjscotti** [comment]
Thank you!  I'll make the Shift JIS fixes that I did previously and try it out later today... Thanks again!

**Comment by sjscotti** [comment]
Working very well!  I'm glad you modified (and I checked) the INSTALL-linux.md file.  I got the `cuDNN Not Found` error and rerunning the cmake/make fixed it.  Thanks for your help!  I'll close this out now.
